/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Javier
 */
public class VentanaHerramientas extends javax.swing.JPanel {

    boolean relleno = false;//Indica si la forma está rellena o no
    public int formaElegida;//indica la herramienta que usaremos
    /**
     * Creates new form VentanaHerramientas
     */
    public VentanaHerramientas() {
        
        initComponents();
        
         ImageIcon miLapiz1 =
                new ImageIcon(
                        new ImageIcon(getClass().getResource("/img/lapiz.PNG"))
                        .getImage()
                        .getScaledInstance(38,38, Image.SCALE_DEFAULT)
                
        );
        
        botonLapiz.setIcon(miLapiz1);
        
        botonLapiz.setOpaque(false);
        botonLapiz.setContentAreaFilled(false);
        botonLapiz.setBorderPainted(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCuadrado = new javax.swing.JButton();
        botonPentagono = new javax.swing.JButton();
        botonEstrella = new javax.swing.JButton();
        botonCirculo2 = new javax.swing.JButton();
        botonTriangulo = new javax.swing.JButton();
        checkRelleno = new javax.swing.JCheckBox();
        botonLapiz = new javax.swing.JButton();

        botonCuadrado.setText("Cuadrado");
        botonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuadradoActionPerformed(evt);
            }
        });

        botonPentagono.setText("Pentágono");
        botonPentagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPentagonoActionPerformed(evt);
            }
        });

        botonEstrella.setText("Estrella");
        botonEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstrellaActionPerformed(evt);
            }
        });

        botonCirculo2.setText("Círculo");
        botonCirculo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCirculo2ActionPerformed(evt);
            }
        });

        botonTriangulo.setText("Triángulo");
        botonTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTrianguloActionPerformed(evt);
            }
        });

        checkRelleno.setText("Relleno");
        checkRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRellenoActionPerformed(evt);
            }
        });

        botonLapiz.setPreferredSize(new java.awt.Dimension(34, 34));
        botonLapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLapizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPentagono, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(botonEstrella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCirculo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonTriangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRelleno)
                            .addComponent(botonCuadrado)
                            .addComponent(botonLapiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkRelleno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCirculo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPentagono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEstrella)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLapiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuadradoActionPerformed
        formaElegida = 4;
    }//GEN-LAST:event_botonCuadradoActionPerformed

    private void botonPentagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPentagonoActionPerformed
        formaElegida = 5;
    }//GEN-LAST:event_botonPentagonoActionPerformed

    private void botonEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstrellaActionPerformed
        formaElegida = 256;
    }//GEN-LAST:event_botonEstrellaActionPerformed

    private void botonCirculo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCirculo2ActionPerformed
        formaElegida = 1;
    }//GEN-LAST:event_botonCirculo2ActionPerformed

    private void botonTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrianguloActionPerformed
        formaElegida = 3;
    }//GEN-LAST:event_botonTrianguloActionPerformed

    private void checkRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRellenoActionPerformed
        relleno = checkRelleno.isSelected();
    }//GEN-LAST:event_checkRellenoActionPerformed

    private void botonLapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLapizActionPerformed
        formaElegida = 0;
        ImageIcon miLapiz2 =
                new ImageIcon(
                        new ImageIcon(getClass().getResource("/img/lapiz2.PNG"))
                        .getImage()
                        .getScaledInstance(38,38, Image.SCALE_DEFAULT)
                
        );
        
        botonLapiz.setIcon(miLapiz2);
    }//GEN-LAST:event_botonLapizActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCirculo2;
    private javax.swing.JButton botonCuadrado;
    private javax.swing.JButton botonEstrella;
    private javax.swing.JButton botonLapiz;
    private javax.swing.JButton botonPentagono;
    private javax.swing.JButton botonTriangulo;
    private javax.swing.JCheckBox checkRelleno;
    // End of variables declaration//GEN-END:variables
}
